### ISSUE TITLE
執行 npm start出現錯誤

### ISSUE THREAD

**Issue by kai456789** [dissipator/gd-utils-noport#1]
這是node版本問題？？ 
root@COPY:~/gd-utils-noport# node -v
v12.18.2

查看token也沒打錯

root@COPY:~/gd-utils-noport# npm start

> teleshellbot@1.0.0 start /root/gd-utils-noport
> node index.js

/root/gd-utils-noport/src/tg.js:9
const { tg_token } = AUTH
        ^

TypeError: Cannot destructure property 'tg_token' of 'AUTH' as it is undefined.
    at Object.<anonymous> (/root/gd-utils-noport/src/tg.js:9:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/root/gd-utils-noport/index.js:6:286)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

**Comment by dissipator** [comment]
应该是配置文件问题，贴出来看看

**Comment by dissipator** [comment]
config.js 呢，或者你更新再试试
